.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

image: python:3

stages:
  - test
  - build

before_script:
  - python -V               # Print out python version for debugging
  - pip install --no-cache-dir --trusted-host pypi.python.org -r requirements-dev.txt

lint check:
  stage: test
  script:
    - flake8 ./src

security check:
  stage: test
  script:
    - bandit -r src

test:
  stage: test
  script:
    - pytest -v --cov=watch_bells --cov-report=term --cov-branch ./test/test_watch_bells.py

build:
  stage: build
  script:
  - pyinstaller --onefile --add-data="assets/icon.png:assets" --add-data="assets/chime_once.wav:assets" --add-binary="assets/chime_twice.wav:assets" src/watch_bells.py
  artifacts:
    paths:
    - dist/watch_bells

build windows:
  extends:
  - .shared_windows_runners
  before_script:
    # https://gitlab.com/gitlab-org/ci-cd/shared-runners/images/gcp/windows-containers/-/issues/13
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install python3 --yes --force --no-progress
    - refreshenv
    - python -V
    - pip install --no-cache-dir --trusted-host pypi.python.org -r requirements-dev.txt
  stage: build
  script:
  - pyinstaller --onefile --add-data="assets/icon.png:assets" --add-data="assets/chime_once.wav:assets" --add-binary="assets/chime_twice.wav:assets" src/watch_bells.py
  artifacts:
    paths:
    - dist/watch_bells
