.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

image: python:3

stages:
  - test
  - build

before_script:
  - python -V               # Print out python version for debugging
  - pip install --no-cache-dir --trusted-host pypi.python.org -r requirements-dev.txt

lint check:
  stage: test
  script:
    - flake8 ./src

security check:
  stage: test
  script:
    - bandit -r src

test:
  stage: test
  script:
    - pytest -v --cov=watch_bells --cov-report=term --cov-branch ./test/test_watch_bells.py

build:
  stage: build
  script:
  - pyinstaller --onefile src/watch_bells.py --add-binary icon.png:icon.png --add-binary chime_once.wav:chime_once.wav --add-binary chime_twice.wav:chime_twice.wav
  artifacts:
    paths:
    - dist/watch_bells

build windows:
  extends:
  - .shared_windows_runners
  stage: build
  script:
  - pyinstaller --onefile src/watch_bells.py --add-binary icon.png:icon.png --add-binary chime_once.wav:chime_once.wav --add-binary chime_twice.wav:chime_twice.wav
  artifacts:
    paths:
    - dist/watch_bells
